name: food_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
  
  fonts:
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-Thin.ttf
          weight: 100 # Thin
        - asset: fonts/Exo2-ExtraLight.ttf
          weight: 200 # ExtraLight
        - asset: fonts/Exo2-Light.ttf
          weight: 300 # Light
        - asset: fonts/Exo2-Regular.ttf
          weight: 400 # Regular
        - asset: fonts/Exo2-Medium.ttf
          weight: 500 # Medium
        - asset: fonts/Exo2-SemiBold.ttf
          weight: 600 # SemiBold
        - asset: fonts/Exo2-Bold.ttf
          weight: 700 # Bold
        - asset: fonts/Exo2-ExtraBold.ttf
          weight: 800 # ExtraBold
        - asset: fonts/Exo2-Black.ttf
          weight: 900 # Black